version: "3.9"
services:
  frontend:
    image: omarsater/private-repo:react-v1.1.2
    environment:
      NODE_ENV: production
    ports:
      - "80:3000"
    networks:
      - my-network
    volumes:
      - _data2:/app
    depends_on:
      - backend
  backend:
    image: omarsater/private-repo:flask-v1.0.0
    ports:
      - "5000:5000"
    networks:
      - my-network
    volumes:
      - _data:/app

networks:
  my-network:
    driver: bridge
volumes:
  _data:
  _data2: