version: "3.9"
services:
  frontend:
    image: omarsater/private-repo:react-v1.1.1
    environment:
      NODE_ENV: production
    ports:
      - "80:3000"
    networks:
      - my-network
    volumes:
      - front_data:/app
    depends_on:
      - backend
  backend:
    image: omarsater/private-repo:flask-v1.1.1
    ports:
      - "5000:5000"
    networks:
      - my-network
    volumes:
      - back_data:/app

networks:
  my-network:
    driver: bridge
volumes:
  front_data:
  back_data: