version: "3.9"
services:
  frontend:
    image: omarsater/private-repo:react-v1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: omarsater/private-repo:flask-v1.0
    ports:
      - "5000:5000"